---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-c=.config/yamllint.yml, -s]
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
      - id: ripsecrets
