---
runner_user: cloud-user
github_account: jackhodgkiss
github_repo: verbose-octo-journey
access_token: "{{ secrets_github_access_token }}"

base_runner_dir: /opt/actions-runner

default_runner_labels:
  - kayobe
  - openstack
  - "{{ kayobe_environment | default(omit) }}"

github_runners:
  staging_runner_01: {}
  staging_runner_02: {}
  staging_runner_03: {}

docker_users:
  - "{{ runner_user }}"
pip_install_packages:
  - name: docker
