---
collections:
  - name: stackhpc.cephadm
    version: 1.14.0
  - name: stackhpc.kayobe_workflows
    version: 1.0.1
roles:
  - name: geerlingguy.pip
    version: 2.2.0
  - name: monolithprojects.github_actions_runner
    version: 1.18.5
  - src: https://github.com/stackhpc/ansible-role-docker.git
    name: geerlingguy.docker
