---
###############################################################################
# Infrastructure VM node configuration.

# User with which to access the infrastructure vm via SSH during bootstrap, in
# order to setup the Kayobe user account.
infra_vm_bootstrap_user: cloud-user

###############################################################################
# Infrastructure VM network interface configuration.

# List of networks to which infrastructure vm nodes are attached.
infra_vm_extra_network_interfaces:
  - public

# List of infrastructure vm volume groups. See mrlesmithjr.manage-lvm role for
# format.
infra_vm_lvm_groups:
  - "{{ lvm_group_rootvg }}"

###############################################################################
# Dummy variable to allow Ansible to accept this file.
workaround_ansible_issue_8743: yes
