name: Run Config Diff

concurrency:
  group: kolla-diff-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  prepare-runner:
    uses: ./.github/workflows/prepare-runner.yml
  run-config-diff:
    strategy:
      matrix:
        environment: ['production', 'staging']
    runs-on: ['kayobe', 'openstack', '${{ matrix.environment }}']
    permissions:
      contents: read
      packages: none
    container:
      image: pulp.infra.os.hodgkiss.cloud/kayobe:${{ needs.prepare-runner.outputs.openstack_release }}-latest
      credentials:
        username: admin
        password: ${{ secrets.REGISTRY_PASSWORD }}
    needs: prepare-runner
    steps:
      - name: Checkout kayobe config
        uses: actions/checkout@v3
        with:
           submodules: true
           path: kayobe-config
           fetch-depth: 0
           ref: ${{ github.ref }}

      - name: Copy checkout to expected location
        run: |
            sudo cp -rf $GITHUB_WORKSPACE/kayobe-config /src
            sudo chown stack:stack -Rf /src

      - name: Run config diff
        run: |
            sudo -E -u stack bash -c '/src/.automation/pipeline/config-diff.sh ${{ github.event.pull_request.base.sha }}'
        env:
          KAYOBE_ENVIRONMENT: '${{ matrix.environment }}'
          KAYOBE_VAULT_PASSWORD: "${{ secrets.KAYOBE_VAULT_PASSWORD }}"
          HOME: '/stack'

      - name: Show summary of changes
        run: |
          diffstat < /tmp/kayobe-config-diff

      - name: Print diff
        run: |
          cat /tmp/kayobe-config-diff
