name: Run Tempest

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: |
          The list of tests to run. This should be a name of file under
          .automation.conf/tempest/load-lists. Defaults to running
          default test suite.
        required: false
        default: 'default'
        type: choice
        options:
          - default
          - tempest-full
      tempest_pattern:
        description: |
          Limit tests to this regex. Takes precedence over testSuite.
      kayobe_environment:
        description: |
          Select the environment the kayobe workflow shall target.
        type: choice
        required: true
        default: 'production'
        options: ['production', 'staging']

jobs:
  prepare-runner:
    uses: ./.github/workflows/prepare-runner.yml
  run-tempest:
    runs-on: ['kayobe', 'openstack', '${{ inputs.kayobe_environment }}']
    permissions:
      contents: read
      packages: none
    container:
      image: pulp.infra.os.hodgkiss.cloud/kayobe:${{ needs.prepare-runner.outputs.openstack_release }}-latest
      credentials:
        username: admin
        password: ${{ secrets.REGISTRY_PASSWORD }}
    concurrency:
      group: format('{0}-{1}', tempest, '${{ inputs.kayobe_environment }}')
      cancel-in-progress: false
    timeout-minutes: 360
    needs: prepare-runner
    steps:
      - name: Checkout kayobe config
        uses: actions/checkout@v3
        with:
          submodules: true
          path: kayobe-config

      - name: Symlink source checkout to expected location
        run: sudo ln -s $PWD/kayobe-config /src

      - name: Run ${{ github.event.inputs.test_suite }} tempest testsuite
        run: |
          /src/.automation/pipeline/tempest.sh -e ansible_user=stack
        env:
          KAYOBE_ENVIRONMENT: '${{ inputs.kayobe_environment }}'
          KAYOBE_VAULT_PASSWORD: "${{ secrets.KAYOBE_VAULT_PASSWORD }}"
          KAYOBE_AUTOMATION_SSH_PRIVATE_KEY: "${{ secrets.KAYOBE_AUTOMATION_SSH_PRIVATE_KEY }}"
          KAYOBE_AUTOMATION_TEMPEST_LOADLIST: '${{ github.event.inputs.test_suite }}'
          TEMPEST_PATTERN: '${{ github.event.inputs.tempest_pattern }}'
          TEMPEST_OPENRC: "${{ secrets.TEMPEST_OPENRC }}"
          HOME: '/stack'

      - name: Print stdout
        run: |
          cat /stack/tempest-artifacts/stdout.log || echo "stdout.log is missing"

      - name: Build artifact
        uses: actions/upload-artifact@v3
        with:
         name: tempest-artifacts
         path: |
           /stack/tempest-artifacts
           !/stack/tempest-artifacts/tempest.log

      - name: Fail if any tests did not pass
        run: |
           test $(wc -l < /stack/tempest-artifacts/failed-tests) -lt 1
